# Generated by Django 3.0.5 on 2020-09-13 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IssueTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comments', models.CharField(max_length=500)),
                ('employ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attd_app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdate', models.DateTimeField()),
                ('todate', models.DateTimeField()),
                ('status', models.CharField(max_length=15)),
                ('Employ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attd_app.Employee')),
            ],
        ),
    ]
